### ISSUE TITLE
How to evaluate ?

### ISSUE THREAD

**Issue by chenllliang** [cwszz/XPR#5]
Hi, thanks for opening the dataset. I wonder that how is the evaluation performed? For example , how many candidate phrases would be there for one retrieval since you mentioned it in your paper (sec 3.4) and how to select the candidates. Maybe I missed it, could you give more information or the example code about the evaluation pipeline ?

**Comment by cwszz** [comment]
@chenllliang Hi,
1. We retrieve phrases from the whole dataset during evaluation and test. 
2. We have released the example code and the model. You can try to run tesh.sh.
We will continue to optimize the code in the future.

**Comment by chenllliang** [comment]
thank you very much
